# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Minjae Joh
tagline:          'Minjae Joh's Personal Blog'
description:      'A blog about linguistics, data science, and more.'
url:              mjayjoh.github.io
baseurl:          /

author:
  name:           'Minjae Joh'
  url:            https://www.linkedin.com/in/johminjae/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mjayjoh
